### ISSUE TITLE
Screen brightness, auto dim does not work 

### ISSUE THREAD

**Issue by haywire-zz** [zenyagami/car-dashdroid#4]
On android 4.2.2 auto dim does not work

**Comment by zenyagami** [comment]
what android version, do you have more information?
seems is not working on android 5.0+

**Comment by haywire-zz** [comment]
Not working on 4.2.2

Not much information can be provided, when I click on the brightness icon or try to adjust manually nothing changes.

**Comment by zenyagami** [comment]
is working in latest build!
